carts/urls.py
from django.conf.urls import url
from . import views

app_name = 'carts'

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    url(r'^$', views.update, name='home'),

    # url(r'^add_product/(?P<product_id>[0-9]+)$', views.add_product, name='add_product'),
    url(r'^add_product/$', views.add_product, name='add_product'),

    url(r'^add_entry/$', views.add_entry, name='add_entry'),

    url(r'^remove_product/(?P<product_id>[0-9]+)$', views.remove_product, name='remove_product'),

    url(r'^quantity/update/(?P<entry_id>[0-9]+)/(?P<number>[0-9]+)/$', views.quantity_update, name='quantity_update'),
    # url(r'^quantity/decrease/(?P<number>[0-9]+)$', views.quantity_decrease, name='quantity_decrease'),

]

portal/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, TemplateView

app_name = 'portal'

urlpatterns = [
    # url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^$', views.home, name='home'),

    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='portal/logout.html'), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),

    url(r'^contact/$', views.contact, name='contact'),

    url(r'^about_us/$', views.AboutUsView.as_view(), name='about_us'),

    # url(r'^$', views.home, name='home'),

]

tawaya_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^convert/', include('lazysignup.urls')),
    url(r'^', include('portal.urls', namespace='portal')),
    url(r'^cart/', include('carts.urls', namespace='carts')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^product/', include('products.urls', namespace='products')),
    url(r'^addresses/', include('addresses.urls', namespace='addresses')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

portal/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, ListView, FormView
from products.models import Product
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import login, authenticate
from carts.models import Cart
from lazysignup.decorators import allow_lazy_user

class RegisterView(FormView):

    template_name = 'portal/register.html'

    form_class = RegisterForm

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "Thanks for registering. You are now logged in.")
        new_user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'],
                                )
        login(self.request, new_user)
        return redirect("portal:home")


class HomeView(TemplateView):
    template_name = 'portal/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_products'] = Product.objects.new_products()
        context['preferred_products'] = Product.objects.preferred_products()
        context['cart'] = Cart.objects.get_request_cart()
        return context


@allow_lazy_user
def home(request):
    context = {}
    context['new_products'] = Product.objects.new_products()
    context['preferred_products'] = Product.objects.preferred_products()
    context['cart'] = Cart.objects.get_request_cart(request)
    return render(request, "portal/home.html", context)


class AboutUsView(TemplateView):
    template_name = 'portal/about_us.html'


def contact(request):
    return render(request, "portal/contact.html")

portal/templates/portal-copy-16may/about_us.html
{% extends "portal/base.html" %}
{% load static %}

{% block custom_links %}
    <link rel="stylesheet" href="{% static "plugins/themify-icons/themify-icons.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/jquery-ui-1.12.1.custom/jquery-ui.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "styles/contact_styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "styles/contact_responsive.css" %}">
{% endblock %}


{% block content %}

<div class="super_container">


	<div class="container contact_container">
		<div class="row">
			<div class="col">

				<!-- Breadcrumbs -->

				<div class="breadcrumbs d-flex flex-row align-items-center">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li class="active"><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Contact</a></li>
					</ul>
				</div>

			</div>
		</div>

		<!-- Map Container -->

		<div class="row">
			<div class="col">
				<div id="google_map">
					<div class="map_container">
						<div id="map"></div>
					</div>
				</div>
			</div>
		</div>

		<!-- Contact Us -->

		<div class="row">

			<div class="col-lg-6 contact_col">
				<div class="contact_contents">
					<h1>Contact Us</h1>
					<p>There are many ways to contact us. You may drop us a line, give us a call or send an email, choose what suits you the most.</p>
					<div>
						<p>(800) 686-6688</p>
						<p>info.deercreative@gmail.com</p>
					</div>
					<div>
						<p>mm</p>
					</div>
					<div>
						<p>Open hours: 8.00-18.00 Mon-Fri</p>
						<p>Sunday: Closed</p>
					</div>
				</div>

				<!-- Follow Us -->

				<div class="follow_us_contents">
					<h1>Follow Us</h1>
					<ul class="social d-flex flex-row">
						<li><a href="#" style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #41a1f6"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #fb4343"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
					</ul>
				</div>

			</div>

			<div class="col-lg-6 get_in_touch_col">
				<div class="get_in_touch_contents">
					<h1>Get In Touch With Us!</h1>
					<p>Fill out the form below to recieve a free and confidential.</p>
					<form action="post">
						<div>
							<input id="input_name" class="form_input input_name input_ph" type="text" name="name" placeholder="Name" required="required" data-error="Name is required.">
							<input id="input_email" class="form_input input_email input_ph" type="email" name="email" placeholder="Email" required="required" data-error="Valid email is required.">
							<input id="input_website" class="form_input input_website input_ph" type="url" name="name" placeholder="Website" required="required" data-error="Name is required.">
							<textarea id="input_message" class="input_ph input_message" name="message"  placeholder="Message" rows="3" required data-error="Please, write us a message."></textarea>
						</div>
						<div>
							<button id="review_submit" type="submit" class="red_button message_submit_btn trans_300" value="Submit">send message</button>
						</div>
					</form>
				</div>
			</div>

		</div>
	</div>

	<!-- Newsletter -->

	<div class="newsletter">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center">
						<h4>Newsletter</h4>
						<p>Subscribe to our newsletter and get 20% off your first purchase</p>
					</div>
				</div>
				<div class="col-lg-6">
					<form action="post">
						<div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center">
							<input id="newsletter_email" type="email" placeholder="Your email" required="required" data-error="Valid email is required.">
							<button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">subscribe</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

{% endblock %}

{% block extrajs %}

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
<script src="{% static "plugins/jquery-ui-1.12.1.custom/jquery-ui.js" %}"></script>
<script src="{% static "js/contact_custom.js" %}"></script>

{% endblock %}

portal/templates/portal-copy-16may/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

{% block full_title %}<title>{% block title %}{% endblock %} | Fariha</title>{% endblock %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Colo Shop Template">
<meta name="viewport" content="width=device-width, initial-scale=1">


{% block common_links %}
    <link rel="stylesheet" type="text/css" href="{% static "styles/bootstrap4/bootstrap.min.css" %}">
    <link href="{% static "plugins/font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/OwlCarousel2-2.2.1/owl.carousel.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/OwlCarousel2-2.2.1/owl.theme.default.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/OwlCarousel2-2.2.1/animate.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "styles/style.css" %}">
{% endblock %}

{% block custom_links %}
{% endblock %}

{% block extrahead %}
{% endblock %}

</head>

<body>

<div class="super_container">

	<!-- Header -->

	<header class="header trans_300">

		<!-- Top Navigation -->

		<div class="top_nav">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<div class="top_nav_left">free shipping on all kondhwa orders over 200 rs.</div>
					</div>
					<div class="col-md-6 text-right">
						<div class="top_nav_right">
							<ul class="top_nav_menu">

								<!-- Currency / Language / My Account -->

								<li class="account">
									<a href="#">
										My Account
										<i class="fa fa-angle-down"></i>
									</a>
									<ul class="account_selection">
                                        {% if not user.is_authenticated %}
                                            <li><a href="{% url "portal:login" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a></li>
                                            <li><a href="{% url "portal:register" %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Register</a></li>
                                        {% else %}
                                            <li><a href="{% url "portal:logout" %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                                            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> My Profile</a></li>
                                        {% endif %}
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Main Navigation -->

		<div class="main_nav_container">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 text-right">
						<div class="logo_container">
							<a href="{% url "portal:home" %}"><span>FARI</span>HA</a>
						</div>
						<nav class="navbar">
							<ul class="navbar_menu">
								<li><a href="{% url "portal:home" %}">home</a></li>
								<li><a href="{% url "products:product_list" %}">all products</a></li>
								<li><a href="#">policies</a></li>
								<li><a href="{% url "portal:about_us" %}">about us</a></li>
							</ul>


							<ul class="navbar_user">
                                <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
								<li class="a"><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>

                                <li class="checkout">
									<a href="{% url "cart:home" %}">
										<i class="fa fa-shopping-cart" aria-hidden="true"></i>
										<span id="checkout_items" class="checkout_items">2</span>
									</a>
								</li>
							</ul>
							<div class="hamburger_container">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</div>

	</header>

	<div class="fs_menu_overlay"></div>
	<div class="hamburger_menu">
		<div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
		<div class="hamburger_menu_content text-right">
			<ul class="menu_top_nav">
				<li class="menu_item has-children">
					<a href="#">
						My Account
						<i class="fa fa-angle-down"></i>
					</a>
					<ul class="menu_selection">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url "portal:login" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a></li>
                            <li><a href="{% url "portal:register" %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Register</a></li>
                        {% else %}
                            <li><a href="{% url "portal:logout" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Logout</a></li>
                            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> My Profile</a></li>
                        {% endif %}
					</ul>
				</li>
				<li class="menu_item"><a href="#">home</a></li>
				<li class="menu_item"><a href="#">shop</a></li>
				<li class="menu_item"><a href="#">promotion</a></li>
				<li class="menu_item"><a href="#">pages</a></li>
				<li class="menu_item"><a href="#">blog</a></li>
				<li class="menu_item"><a href="#">contact</a></li>
			</ul>
		</div>
	</div>

    {% block content %}
    {% endblock %}

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
						<ul class="footer_nav">
							<li><a href="#">Blog</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="contact.html">Contact us</a></li>
						</ul>
					</div>
				</div>


				<div class="col-lg-6">
					<div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
						<ul>
							<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
            <h4 style="color: #fe4c50">Fariha Fassions</h4>
			<div class="row">
				<div class="col-lg-12">
					<div class="footer_nav_container">
						<div class="cr">©2018 All Rights Reserverd. This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#">Colorlib</a></div>
					</div>
				</div>
			</div>
		</div>
	</footer>

</div>

{% block common_scripts %}
    <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "styles/bootstrap4/popper.js" %}"></script>
    <script src="{% static "styles/bootstrap4/bootstrap.min.js" %}"></script>
    <script src="{% static "plugins/Isotope/isotope.pkgd.min.js" %}"></script>
    <script src="{% static "plugins/OwlCarousel2-2.2.1/owl.carousel.js" %}"></script>
    <script src="{% static "plugins/easing/easing.js" %}"></script>
{% endblock %}

{% block extrajs %}
        <script src="{% static "js/custom.js" %}"></script>
{% endblock %}

</body>

</html>

portal/templates/portal-copy-16may/contact.html
{% extends "portal/base.html" %}

{% block custom_links %}
    <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="styles/contact_styles.css">
    <link rel="stylesheet" type="text/css" href="styles/contact_responsive.css">
{% endblock %}


{% block content %}

<div class="super_container">


	<div class="container contact_container">
		<div class="row">
			<div class="col">

				<!-- Breadcrumbs -->

				<div class="breadcrumbs d-flex flex-row align-items-center">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li class="active"><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i>Contact</a></li>
					</ul>
				</div>

			</div>
		</div>

		<!-- Map Container -->

		<div class="row">
			<div class="col">
				<div id="google_map">
					<div class="map_container">
						<div id="map"></div>
					</div>
				</div>
			</div>
		</div>

		<!-- Contact Us -->

		<div class="row">

			<div class="col-lg-6 contact_col">
				<div class="contact_contents">
					<h1>Contact Us</h1>
					<p>There are many ways to contact us. You may drop us a line, give us a call or send an email, choose what suits you the most.</p>
					<div>
						<p>(800) 686-6688</p>
						<p>info.deercreative@gmail.com</p>
					</div>
					<div>
						<p>mm</p>
					</div>
					<div>
						<p>Open hours: 8.00-18.00 Mon-Fri</p>
						<p>Sunday: Closed</p>
					</div>
				</div>

				<!-- Follow Us -->

				<div class="follow_us_contents">
					<h1>Follow Us</h1>
					<ul class="social d-flex flex-row">
						<li><a href="#" style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #41a1f6"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #fb4343"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
					</ul>
				</div>

			</div>

			<div class="col-lg-6 get_in_touch_col">
				<div class="get_in_touch_contents">
					<h1>Get In Touch With Us!</h1>
					<p>Fill out the form below to recieve a free and confidential.</p>
					<form action="post">
						<div>
							<input id="input_name" class="form_input input_name input_ph" type="text" name="name" placeholder="Name" required="required" data-error="Name is required.">
							<input id="input_email" class="form_input input_email input_ph" type="email" name="email" placeholder="Email" required="required" data-error="Valid email is required.">
							<input id="input_website" class="form_input input_website input_ph" type="url" name="name" placeholder="Website" required="required" data-error="Name is required.">
							<textarea id="input_message" class="input_ph input_message" name="message"  placeholder="Message" rows="3" required data-error="Please, write us a message."></textarea>
						</div>
						<div>
							<button id="review_submit" type="submit" class="red_button message_submit_btn trans_300" value="Submit">send message</button>
						</div>
					</form>
				</div>
			</div>

		</div>
	</div>

	<!-- Newsletter -->

	<div class="newsletter">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center">
						<h4>Newsletter</h4>
						<p>Subscribe to our newsletter and get 20% off your first purchase</p>
					</div>
				</div>
				<div class="col-lg-6">
					<form action="post">
						<div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center">
							<input id="newsletter_email" type="email" placeholder="Your email" required="required" data-error="Valid email is required.">
							<button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">subscribe</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

{% endblock %}

{% block extrajs %}

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
<script src="plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="js/contact_custom.js"></script>

{% endblock %}

portal/templates/portal-copy-16may/login.html
{% extends "portal/base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block custom_links %}
    <link rel="stylesheet" type="text/css" href="{% static "styles/main_styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "styles/responsive.css" %}">
{% endblock %}

{% block content %}

    <br><br><br><br><br><br><br>
    <div class="jumbotron container text-center">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button class="red_button shop_now_button" type="submit">Login</button>
        </form>

    </div>

{% endblock %}

portal/templates/portal-copy-16may/logout.html
{% extends "portal/base.html" %}
{% load static %}

{% block title %}Logout{% endblock %}

{% block custom_links %}
    <link rel="stylesheet" type="text/css" href="{% static "styles/main_styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "styles/responsive.css" %}">
{% endblock %}

{% block content %}

    <br><br><br><br><br><br><br>
    <div class="jumbotron container text-center">

        <h4>Thank you for being with us..</h4>
        <a href="{% url "portal:login" %}">Login again</a>

    </div>

{% endblock %}

portal/templates/portal-copy-16may/register.html
{% extends "portal/base.html" %}
{% load static %}

{% block title %}Register{% endblock %}

{% block custom_links %}
    <link rel="stylesheet" type="text/css" href="{% static "styles/main_styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "styles/responsive.css" %}">
{% endblock %}

{% block content %}

    <br><br><br><br><br><br><br>
    <div class="jumbotron container text-center">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button class="red_button shop_now_button" type="submit">Register</button>
        </form>

    </div>

{% endblock %}