carts/urls.py
from django.conf.urls import url
from . import views

app_name = 'carts'

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    url(r'^$', views.update, name='home'),

    # url(r'^add_product/(?P<product_id>[0-9]+)$', views.add_product, name='add_product'),
    url(r'^add_product/$', views.add_product, name='add_product'),

    url(r'^add_entry/$', views.add_entry, name='add_entry'),

    url(r'^remove_product/(?P<product_id>[0-9]+)$', views.remove_product, name='remove_product'),

    url(r'^quantity/update/(?P<entry_id>[0-9]+)/(?P<number>[0-9]+)/$', views.quantity_update, name='quantity_update'),
    # url(r'^quantity/decrease/(?P<number>[0-9]+)$', views.quantity_decrease, name='quantity_decrease'),

]

portal/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, TemplateView

app_name = 'portal'

urlpatterns = [
    # url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^$', views.home, name='home'),

    url(r'^login/$', LoginView.as_view(template_name='portal/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='portal/logout.html'), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),

    url(r'^contact/$', views.contact, name='contact'),

    url(r'^about_us/$', views.AboutUsView.as_view(), name='about_us'),

    # url(r'^$', views.home, name='home'),

]

products/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .filters import ProductFilter
from django_filters.views import FilterView

app_name = 'products'

urlpatterns = [
    url(r'^detail/(?P<product_id>[0-9]+)/$', views.ProductDetailView.as_view(), name='detail'),
    url(r'^list/$', views.ProductListView.as_view(), name='list'),
    url(r'^search/$', FilterView.as_view(filterset_class=ProductFilter,
                                         template_name='products/search.html'), name='search')
]

tawaya_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^convert/', include('lazysignup.urls')),
    url(r'^', include('portal.urls', namespace='portal')),
    url(r'^cart/', include('carts.urls', namespace='carts')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^product/', include('products.urls', namespace='products')),
    url(r'^addresses/', include('addresses.urls', namespace='addresses')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from .managers import ProductManager
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.conf import settings
from django.db.models.signals import post_save, pre_save
from django.conf import settings
from django.utils.text import slugify

USER_MODEL = settings.AUTH_USER_MODEL


def add_slug(sender, instance, *args, **kwargs):
    slug_text = slugify(instance.name)
    if instance.slug != slug_text:
        instance.slug = slug_text
        instance.save()


class Size(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(blank=True, null=True)
    abbrevation = models.CharField(max_length=8)
    length = models.CharField(max_length=16)
    unit = models.CharField(max_length=16, default="Inch")
    details = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @property
    def get_text(self):
        return self.abbrevation


post_save.connect(add_slug, sender=Size)


class Color(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(blank=True, null=True)
    abbrevation = models.CharField(max_length=8)
    hex_code = models.CharField(max_length=7, default="#FF0000")
    details = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @property
    def get_hex_code(self):
        return self.hex_code

    @property
    def get_text(self):
        return self.abbrevation


post_save.connect(add_slug, sender=Color)


class PhotoPosition(models.Model):
    name = models.CharField(max_length=32)
    abbrevation = models.CharField(max_length=8)
    details = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @property
    def get_text(self):
        return self.abbrevation


class ProductPhoto(models.Model):
    photo = models.ImageField(upload_to='products/product_photos/')
    color = models.ForeignKey(Color, on_delete=models.PROTECT)
    position = models.ForeignKey(PhotoPosition, on_delete=models.PROTECT)
    product = models.ForeignKey('Product', on_delete=models.PROTECT)
    base_photo = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {}".format(self.position, self.product.name)

    @property
    def get_photo_url(self):
        return self.photo.url

    @property
    def get_position(self):
        return self.position.get_text


class Category(models.Model):
    name = models.CharField(max_length=16)
    slug = models.SlugField(blank=True, null=True)
    details = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @property
    def get_text(self):
        return self.name


post_save.connect(add_slug, sender=Category)


class Product(models.Model):

    PREFERENCE_CHOICES = ((1, 'Excellent'), (2, 'Very Good'), (3, 'Good'), (4, 'Average'))

    name = models.CharField(max_length=16)
    slug = models.SlugField(blank=True, null=True)
    headline = models.CharField(max_length=48)
    details = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    actual_price = models.DecimalField(max_digits=6, decimal_places=2)
    sizes = models.ManyToManyField(Size)
    colors = models.ManyToManyField(Color)
    preference = models.PositiveSmallIntegerField(default=2, choices=PREFERENCE_CHOICES)

    current_ocassion = models.BooleanField(default=False)

    categories = models.ManyToManyField(Category)
    tag = models.CharField(max_length=5, blank=True)

    available_pieces = models.PositiveSmallIntegerField(default=100)
    out_of_stock = models.BooleanField(default=False)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    active = models.BooleanField(default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

    @property
    def get_headline(self):
        return self.headline

    @property
    def get_display_name(self):
        return self.headline

    @property
    def get_price(self):
        return self.price

    @property
    def get_photos(self):
        return self.productphoto_set.all()

    @property
    def get_base_photo_url(self):
        return self.productphoto_set.get(base_photo=True).photo.url

    @property
    def get_non_base_photos(self):
        return self.productphoto_set.filter(base_photo=False)

    @property
    def get_off_price(self):
        return self.price - self.actual_price

    @property
    def get_colors(self):
        return self.colors.all()

    @property
    def get_color_hex_codes(self):
        return self.colors.values_list('hex_code', flat=True)

    @property
    def get_color_names(self):
        return self.colors.values_list('name', flat=True)

    @property
    def get_sizes(self):
        return self.sizes.all()

    @property
    def get_absolute_url(self):
        return reverse_lazy('products:product_detail', kwargs={'product_id': self.id})

    @property
    def get_detail_view_url(self):
        return reverse_lazy('products:detail', kwargs={'product_id': self.id})

    @property
    def get_add_to_cart_url(self):
        return reverse_lazy('carts:add_product', kwargs={'product_id': self.id})

    @property
    def get_remove_from_cart_url(self):
        return reverse_lazy('carts:remove_product', kwargs={'product_id': self.id})

    def clean(self):
        if self.productphoto_set.filter(base_photo=True).count() != 1:
            raise ValidationError("There should be exact 1 base photo")


post_save.connect(add_slug, sender=Product)

portal/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

portal/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, ListView, FormView
from products.models import Product
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import login, authenticate
from carts.models import Cart
from lazysignup.decorators import allow_lazy_user

class RegisterView(FormView):

    template_name = 'portal/register.html'

    form_class = RegisterForm

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "Thanks for registering. You are now logged in.")
        new_user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'],
                                )
        login(self.request, new_user)
        return redirect("portal:home")


class HomeView(TemplateView):
    template_name = 'portal/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_products'] = Product.objects.new_products()
        context['preferred_products'] = Product.objects.preferred_products()
        context['cart'] = Cart.objects.get_request_cart()
        return context


@allow_lazy_user
def home(request):
    context = {}
    context['new_products'] = Product.objects.new_products()
    context['preferred_products'] = Product.objects.preferred_products()
    context['cart'] = Cart.objects.get_request_cart(request)
    return render(request, "portal/home.html", context)


class AboutUsView(TemplateView):
    template_name = 'portal/about_us.html'


def contact(request):
    return render(request, "portal/contact.html")

portal/templates/portal/base2.html
{% load static %}
{% load i18n lazysignup_tags %}

<!DOCTYPE html>
<html lang="en">
<head>

{% block full_title %}<title>{% block title %}{% endblock %} | Fariha</title>{% endblock %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Colo Shop Template">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>


{% block common_links %}

    <link rel="stylesheet" type="text/css" href="{% static "styles/bootstrap4/bootstrap.min.css" %}">
    <link href="{% static "plugins/font-awesome-4.7.0/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/OwlCarousel2-2.2.1/owl.carousel.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/OwlCarousel2-2.2.1/owl.theme.default.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "plugins/OwlCarousel2-2.2.1/animate.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "styles/style.css" %}">
{% endblock %}

{% block custom_links %}
{% endblock %}

{% block extrahead %}
{% endblock %}

</head>

<body>


{% if messages %}
    {% for message in messages %}
        <span class="alert alert-{{ message.tags }}">{{ message }}</span>
    {% endfor %}
{% endif %}

<div class="super_container">

	<!-- Header -->

	<header class="header trans_300">

		<!-- Top Navigation -->

		<div class="top_nav">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<div class="top_nav_left">free shipping on all kondhwa orders over 200 rs.</div>
					</div>
					<div class="col-md-6 text-right">
						<div class="top_nav_right">
							<ul class="top_nav_menu">

								<!-- Currency / Language / My Account -->

								<li class="account">
									<a href="#">
										My Account
										<i class="fa fa-angle-down"></i>
									</a>
									<ul class="account_selection">
                                        {% if user|is_lazy_user %}
                                            <li><a href="{% url "portal:login" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a></li>
                                            <li><a href="{% url "lazysignup_convert" %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Register</a></li>
                                        {% elif not user|is_lazy_user and user.is_authenticated  %}
                                            <li><a href="{% url "portal:logout" %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                                            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> My Profile</a></li>
                                        {% elif not user.is_authenticated %}
                                            <li><a href="{% url "portal:login" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a></li>
                                            <li><a href="{% url "portal:register" %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Register</a></li>
                                        {% endif %}
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>


		<!-- Main Navigation -->

		<div class="main_nav_container">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 text-right">
						<div class="logo_container">
							<a href="{% url "portal:home" %}"><span>FARI</span>HA</a>
						</div>
						<nav class="navbar">
							<ul class="navbar_menu">
								<li><a href="{% url "portal:home" %}">home</a></li>
								<li><a href="{% url "products:product_list" %}">all products</a></li>
								<li><a href="#">policies</a></li>
								<li><a href="{% url "portal:about_us" %}">about us</a></li>
							</ul>


							<ul class="navbar_user">
                                <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
								<li class="a"><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>

                                <li class="checkout">
									<a href="{% url "carts:home" %}">
										<i class="fa fa-shopping-cart" aria-hidden="true"></i>
										<span id="checkout_items" class="checkout_items">2</span>
									</a>
								</li>
							</ul>
							<div class="hamburger_container">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</div>

	</header>

	<div class="fs_menu_overlay"></div>
	<div class="hamburger_menu">
		<div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
		<div class="hamburger_menu_content text-right">
			<ul class="menu_top_nav">
				<li class="menu_item has-children">
					<a href="#">
						My Account
						<i class="fa fa-angle-down"></i>
					</a>
					<ul class="menu_selection">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url "portal:login" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a></li>
                            <li><a href="{% url "portal:register" %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Register</a></li>
                        {% else %}
                            <li><a href="{% url "portal:logout" %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Logout</a></li>
{#                            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> My Profile</a></li>#}
                        {% endif %}
					</ul>
				</li>
				<li class="menu_item"><a href="#">home</a></li>
				<li class="menu_item"><a href="#">shop</a></li>
				<li class="menu_item"><a href="#">promotion</a></li>
				<li class="menu_item"><a href="#">pages</a></li>
				<li class="menu_item"><a href="#">blog</a></li>
				<li class="menu_item"><a href="#">contact</a></li>
			</ul>
		</div>
	</div>
    <span style="color:red!important;" class=" alert alert-danger btn-block">Soemething in alert</span>


    {% block content %}
    {% endblock %}

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
						<ul class="footer_nav">
							<li><a href="#">Blog</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="contact.html">Contact us</a></li>
						</ul>
					</div>
				</div>


				<div class="col-lg-6">
					<div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
						<ul>
							<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
            <h4 style="color: #fe4c50">Fariha Fassions</h4>
			<div class="row">
				<div class="col-lg-12">
					<div class="footer_nav_container">
						<div class="cr">©2018 All Rights Reserverd. This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#">Colorlib</a></div>
					</div>
				</div>
			</div>
		</div>
	</footer>

</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<script type="text/javascript">
    $('.addToCartButton').click(function(){
    var product_id;
    product_id = $(this).attr("data-product_id");
    $.ajax(
    {
        type:"GET",
        url: "{% url "carts:add_product" %}",
        data:{
            product_id: product_id
        },
        success: function( data )
        {
            $( '#product'+ product_id ).remove();
            $( '#message' ).text(data);
        }
     })
});
</script>

{% block common_scripts %}
    <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "styles/bootstrap4/popper.js" %}"></script>
    <script src="{% static "styles/bootstrap4/bootstrap.min.js" %}"></script>
    <script src="{% static "plugins/Isotope/isotope.pkgd.min.js" %}"></script>
    <script src="{% static "plugins/OwlCarousel2-2.2.1/owl.carousel.js" %}"></script>
    <script src="{% static "plugins/easing/easing.js" %}"></script>
{% endblock %}

{% block extrajs %}
        <script src="{% static "js/custom.js" %}"></script>
{% endblock %}

{% block extrascript %}
{% endblock %}

</body>

</html>

portal/templates/portal/contact.html
{% extends "portal/base.html" %}


{% block content %}

	<!-- Content page -->
	<section class="bg0 p-t-104 p-b-116">
		<div class="container">
			<div class="flex-w flex-tr">
				<div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
					<form>
						<h4 class="mtext-105 cl2 txt-center p-b-30">
							Send Us A Message
						</h4>

						<div class="bor8 m-b-20 how-pos4-parent">
							<input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="text" name="email" placeholder="Your Email Address">
							<img class="how-pos4 pointer-none" src="images/icons/icon-email.png" alt="ICON">
						</div>

						<div class="bor8 m-b-30">
							<textarea class="stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25" name="msg" placeholder="How Can We Help?"></textarea>
						</div>

						<button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
							Submit
						</button>
					</form>
				</div>

				<div class="size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md">
					<div class="flex-w w-full p-b-42">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-map-marker"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Address
							</span>

							<p class="stext-115 cl6 size-213 p-t-18">
								Coza Store Center 8th floor, 379 Hudson St, New York, NY 10018 US
							</p>
						</div>
					</div>

					<div class="flex-w w-full p-b-42">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-phone-handset"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Lets Talk
							</span>

							<p class="stext-115 cl1 size-213 p-t-18">
								+1 800 1236879
							</p>
						</div>
					</div>

					<div class="flex-w w-full">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-envelope"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Sale Support
							</span>

							<p class="stext-115 cl1 size-213 p-t-18">
								contact@example.com
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>	
	
	
	<!-- Map -->
	<div class="map">
		<div class="size-303" id="google_map" data-map-x="40.691446" data-map-y="-73.886787" data-pin="images/icons/pin.png" data-scrollwhell="0" data-draggable="1" data-zoom="11"></div>
	</div>



{% endblock %}

portal/templates/portal/header.html
	{% load static %}
    <header>
		<!-- Header desktop -->
		<div class="container-menu-desktop">
			<!-- Topbar -->
			<div class="top-bar">
				<div class="content-topbar flex-sb-m h-full container">
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>

					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m trans-04 p-lr-25">
							Help & FAQs
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							My Account
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							EN
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							USD
						</a>
					</div>
				</div>
			</div>

			<div class="wrap-menu-desktop">
				<nav class="limiter-menu-desktop container">

					<!-- Logo desktop -->
					<a href="#" class="logo">
						<img src="{% static "images/icons/logo-01.png" %}" alt="IMG-LOGO">
					</a>

					<!-- Menu desktop -->
					<div class="menu-desktop">
						<ul class="main-menu">
							<li class="active-menu">
								<a href="{% url "portal:home" %}">Home</a>
							</li>

							<li>
								<a href="{% url "products:list" %}">All Products</a>
							</li>

							<li class="label1" data-label1="hot">
								<a href="shoping-cart.html">Features</a>
							</li>

							<li>
								<a href="{% url "portal:about_us" %}">About</a>
							</li>

							<li>
								<a href="{% url "portal:contact" %}">Contact</a>
							</li>
						</ul>
					</div>

					<!-- Icon header -->
					<div class="wrap-icon-header flex-w flex-r-m">
						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
							<i class="zmdi zmdi-search"></i>
						</div>

						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="2">
							<i class="zmdi zmdi-shopping-cart"></i>
						</div>

						<a href="#" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti" data-notify="0">
							<i class="zmdi zmdi-favorite-outline"></i>
						</a>
					</div>
				</nav>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap-header-mobile">
			<!-- Logo moblie -->
			<div class="logo-mobile">
				<a href="index.html"><img src="{% static "images/icons/logo-01.png" %}" alt="IMG-LOGO"></a>
			</div>

			<!-- Icon header -->
			<div class="wrap-icon-header flex-w flex-r-m m-r-15">
				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search">
					<i class="zmdi zmdi-search"></i>
				</div>

				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart" data-notify="2">
					<i class="zmdi zmdi-shopping-cart"></i>
				</div>

				<a href="#" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti" data-notify="0">
					<i class="zmdi zmdi-favorite-outline"></i>
				</a>
			</div>

			<!-- Button show menu -->
			<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
				</span>
			</div>
		</div>


		<!-- Menu Mobile -->
		<div class="menu-mobile">
			<ul class="topbar-mobile">
				<li>
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>
				</li>

				<li>
					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m p-lr-10 trans-04">
							Help & FAQs
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							My Account
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							EN
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							USD
						</a>
					</div>
				</li>
			</ul>

			<ul class="main-menu-m">
				<li>
					<a href="{% url "portal:home" %}">Home</a>
				</li>

				<li>
					<a href="{% url "products:list" %}">All Products</a>
				</li>

				<li>
					<a href="shoping-cart.html" class="label1 rs1" data-label1="hot">Features</a>
				</li>

				<li>
                    <a href="{% url "portal:about_us" %}">About</a>
				</li>

				<li>
					<a href="{% url "portal:contact" %}">Contact</a>
				</li>
			</ul>
		</div>

		<!-- Modal Search -->
		<div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
			<div class="container-search-header">
				<button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
					<img src="{% static "images/icons/icon-close2.png" %}" alt="CLOSE">
				</button>

				<form class="wrap-search-header flex-w p-l-15">
					<button class="flex-c-m trans-04">
						<i class="zmdi zmdi-search"></i>
					</button>
					<input class="plh3" type="text" name="search" placeholder="Search...">
				</form>
			</div>
		</div>
	</header>

portal/templates/portal/login.html
{% extends "portal/base.html" %}


{% block content %}

	<!-- Content page -->
	<section class="bg0 p-t-104 p-b-116">
		<div class="container">
			<div class="flex-w flex-tr">

				<div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
					<form>
						<h4 class="mtext-105 cl2 txt-center p-b-30">
							Login
						</h4>

						<div class="bor8 m-b-20 how-pos4-parent">
							<input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="text" name="email" placeholder="Your Email Address">
							<img class="how-pos4 pointer-none" src="images/icons/icon-email.png" alt="ICON">
						</div>

						<div class="bor8 m-b-30">
							<textarea class="stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25" name="msg" placeholder="How Can We Help?"></textarea>
						</div>

						<button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
							Submit
						</button>
					</form>
				</div>


			</div>
		</div>
	</section>


	<!-- Map -->
	<div class="map">
		<div class="size-303" id="google_map" data-map-x="40.691446" data-map-y="-73.886787" data-pin="images/icons/pin.png" data-scrollwhell="0" data-draggable="1" data-zoom="11"></div>
	</div>



{% endblock %}